export const filterLists = {
    filterLabels: ['new', 'off_the_grid', 'iconic_cities', 'rooms', 'creative_spaces', 'boats', 'grand_pianos', 'vineyards', 'historical_homes', 'mansions', 'lake', 'bed_and_breakfasts', 'farms', 'windmills', 'towers', 'treehouses', 'skiing', 'earth_homes', 'beach', 'amazing_views', 'countryside', 'a_frames', 'desert', 'design', 'beachfront', 'caves', 'national_parks', 'castles', 'lakefront', 'islands', 'trulli', 'tropical', 'cabins', 'campers', 'camping', 'arctic', 'tiny_homes', 'surfing', 'barns', 'cycladic_homes', 'hanoks', 'ryokans', 'domes', 'shepard_huts', 'yurts', 'minsus', 'casas_particulares'],

    placeTypeItems: [{ value: 'any', label: 'Any type' }, { value: 'room' }, { value: 'entire home' }],
    bbbItems: [{ value: 'any' }, { value: 1 }, { value: 2 }, { value: 3 }, { value: 4 }, { value: 5 }, { value: 6 }, { value: 7 }, { value: '8+' },],
    propTypeItems: [{ value: 'house' }, { value: 'apartment' }, { value: 'guesthouse' }, { value: 'hotel' }],
    amenityEssentialsShown: [{ value: 'wifi' }, { value: 'kitchen' }, { value: 'washer' }, { value: 'dryer' }, { value: 'air_conditioning', label: 'air conditioning' }, { value: 'heating' }],
    amenityEssentialsHidden: [{ value: 'dedicated_workspace', label: 'dedicated workspace' }, { value: 'TV' }, { value: 'hair_dryer', label: 'hair dryer' }, { value: 'iron' }],
    amenityFeatures: [{ value: 'pool' }, { value: 'hot_tub', label: 'hot tub' }, { value: 'free_parking', label: 'free parking' }, { value: 'ev_charger', label: 'ev charger' }, { value: 'crib' }, { value: 'king_bed', label: 'king bed' }, { value: 'gym' }, { value: 'BBQ_grill', label: 'BBQ grill' }, { value: 'breakfast' }, { value: 'indoor_fireplace', label: 'indoor fireplace' }, { value: 'smoking_allowed', label: 'smoking allowed' }],
    amenityLocation: [{ value: 'beachfront' }, { value: 'waterfront' }],
    amenitySafety: [{ value: 'smoke_alarm', label: 'smoke alarm' }, { value: 'carbon_monoxide-alarm', label: 'carbon monoxide alarm' }],
    hostLngsShown: [{ value: 'english' }, { value: 'french' }, { value: 'german' }, { value: 'japanese' }],
    hostLngsHidden: [{ value: 'italian' }, { value: 'russian' }, { value: 'spanish' }, { value: 'chinese (Simplified)' }, { value: 'arabic' }, { value: 'hindi' }, { value: 'portuguese' }, { value: 'turkish' }, { value: 'dutch' }, { value: 'korean' }, { value: 'thai' }, { value: 'greek' }, { value: 'hebrew' }, { value: 'polish' }, { value: 'tagalog' }, { value: 'danish' }, { value: 'swedish' }, { value: 'norwegian' }, { value: 'finnish' }, { value: 'czech' }, { value: 'hungarian' }],
    accessEntrance: [{ value: 'step-free-entrance', label: 'Step-free guest entrance' }, { value: 'wide-entrance', label: 'Guest entrance wider than 32 inches' }, { value: 'accessible-parking', label: 'Accessible parking spot' }, { value: 'step-free-path-to-entrance', label: 'Step-free path to the guest entrance' }],
    accessBedrooms: [{ value: 'step-free-bedroom', label: 'Step-free bedroom access' }, { value: 'wide-bedroom', label: 'Bedroom entrance wider than 32 inches' }],
    accessBathrooms: [{ value: 'step-free-bathroom', label: 'Step-free bathroom access' }, { value: 'wide-bathroom', label: 'Bathroom entrance wider than 32 inches' }, { value: 'Shower-bar', label: 'Shower grab bar' }, { value: 'Toilet-bar', label: 'Toilet grab bar' }, { value: 'Step-free-shower', label: 'Step-free shower' }, { value: 'bath-chair', label: 'Shower or bath chair' }],
    accessEquipment: [{ value: 'hoist', label: 'Ceiling or mobile hoist' }]
}